### PR TITLE
Stenotype sample board

### PR DESCRIPTION
**Pull request by Twey**
Adds basic steno support.

It's not the prettiest but it was enough for me to get steno working with Plover on my Sval :)

I've added the script, `resolve_enums.py`, that I used to add steno actioncodes to the in-repo `keycodes.h`.  So long as you have `pycparser` and `cpp` available, you can run it like:
```shellsession
$ ./resolve_enums.py /path/to/vial-qmk/quantum/steno_keycodes.h > keycodes.h
```

(or any other file(s) you might fancy — `steno_keycodes.h` includes the base `keycodes.h` plus the steno actioncodes).

### CODE REVIEW

**Comment by captdeaf** [comment]
> when I was writing it the contents of the <div>s in the sample boards was used as the visible label, but now it seems it's reset to the raw actioncode name

When I started tweaking key rendering (e.g: CTRL_T is now a blue box w/ a gray bar on top), the kb-norender items started coming out quite poorly, so I reverted to using their names. I'm still debating either getting rid of the kb-norender class entirely or just reduce the amount of places it's used in. But keeping rendering identical between mainboard and sample boards is now my priority with that rendering.

**Comment by Twey** [comment]
Got it.  I found where to add the metadata so I don't need `kb-norender` any more anyway :)  I've removed it.

**Comment by captdeaf** [comment]
Looking good, have you tried this on a Steno keyboard?

I don't see any reason it wouldn't work, especially given all it is, is a sample board.

Keybard is currently in feature freeze pending UX/UI completion and hopefully release of a "Beta 1.0", but will add this afterwards!

**Comment by Twey** [comment]
Yep, it does require `STENO_ENABLE = yes` and `STENO_PROTOCOL = txbolt|geminipr|…` on the firmware.  But all working well on my Sval after that :)

**Comment by captdeaf** [comment]
LGTM, merging

**Pull request merged**
